DROP DATABASE IF EXISTS guest01;
CREATE DATABASE guest01;
CREATE TABLE guest01.data (name VARCHAR(32), value int);
INSERT INTO guest01.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest02;
CREATE DATABASE guest02;
CREATE TABLE guest02.data (name VARCHAR(32), value int);
INSERT INTO guest02.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest03;
CREATE DATABASE guest03;
CREATE TABLE guest03.data (name VARCHAR(32), value int);
INSERT INTO guest03.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest04;
CREATE DATABASE guest04;
CREATE TABLE guest04.data (name VARCHAR(32), value int);
INSERT INTO guest04.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest05;
CREATE DATABASE guest05;
CREATE TABLE guest05.data (name VARCHAR(32), value int);
INSERT INTO guest05.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest06;
CREATE DATABASE guest06;
CREATE TABLE guest06.data (name VARCHAR(32), value int);
INSERT INTO guest06.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest07;
CREATE DATABASE guest07;
CREATE TABLE guest07.data (name VARCHAR(32), value int);
INSERT INTO guest07.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest08;
CREATE DATABASE guest08;
CREATE TABLE guest08.data (name VARCHAR(32), value int);
INSERT INTO guest08.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest09;
CREATE DATABASE guest09;
CREATE TABLE guest09.data (name VARCHAR(32), value int);
INSERT INTO guest09.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest10;
CREATE DATABASE guest10;
CREATE TABLE guest10.data (name VARCHAR(32), value int);
INSERT INTO guest10.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest11;
CREATE DATABASE guest11;
CREATE TABLE guest11.data (name VARCHAR(32), value int);
INSERT INTO guest11.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest12;
CREATE DATABASE guest12;
CREATE TABLE guest12.data (name VARCHAR(32), value int);
INSERT INTO guest12.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest13;
CREATE DATABASE guest13;
CREATE TABLE guest13.data (name VARCHAR(32), value int);
INSERT INTO guest13.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest14;
CREATE DATABASE guest14;
CREATE TABLE guest14.data (name VARCHAR(32), value int);
INSERT INTO guest14.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest15;
CREATE DATABASE guest15;
CREATE TABLE guest15.data (name VARCHAR(32), value int);
INSERT INTO guest15.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest16;
CREATE DATABASE guest16;
CREATE TABLE guest16.data (name VARCHAR(32), value int);
INSERT INTO guest16.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest17;
CREATE DATABASE guest17;
CREATE TABLE guest17.data (name VARCHAR(32), value int);
INSERT INTO guest17.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest18;
CREATE DATABASE guest18;
CREATE TABLE guest18.data (name VARCHAR(32), value int);
INSERT INTO guest18.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest19;
CREATE DATABASE guest19;
CREATE TABLE guest19.data (name VARCHAR(32), value int);
INSERT INTO guest19.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest20;
CREATE DATABASE guest20;
CREATE TABLE guest20.data (name VARCHAR(32), value int);
INSERT INTO guest20.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest21;
CREATE DATABASE guest21;
CREATE TABLE guest21.data (name VARCHAR(32), value int);
INSERT INTO guest21.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest22;
CREATE DATABASE guest22;
CREATE TABLE guest22.data (name VARCHAR(32), value int);
INSERT INTO guest22.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest23;
CREATE DATABASE guest23;
CREATE TABLE guest23.data (name VARCHAR(32), value int);
INSERT INTO guest23.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest24;
CREATE DATABASE guest24;
CREATE TABLE guest24.data (name VARCHAR(32), value int);
INSERT INTO guest24.data VALUES ('counter', 0);
DROP DATABASE IF EXISTS guest25;
CREATE DATABASE guest25;
CREATE TABLE guest25.data (name VARCHAR(32), value int);
INSERT INTO guest25.data VALUES ('counter', 0);
